spring:
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  application:
    name: doga
  jpa:
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/covid19
    driver: org.postgresql.Driver

server:
   servlet:
     contextPath: /covid-negative


#Redis Configuration
redis:
  default:
    host: localhost
    port: 6379
    password: password
    ttl: 2

covid:
  data:
    statisticsUrl: "https://api.covid19india.org/data.json"